'use client'

import { useState } from 'react'
import Link from 'next/link'
import FreeTrialBanner from '../../components/FreeTrialBanner'

export default function TaxCalculatorPage() {
  const [inputs, setInputs] = useState({
    grossIncome: '',
    businessExpenses: '',
    filingStatus: 'single',
    state: 'federal-only',
    deductions: '',
    credits: '',
    taxYear: '2024'
  })

  const [results, setResults] = useState({
    taxableIncome: 0,
    federalTax: 0,
    stateTax: 0,
    totalTax: 0,
    effectiveRate: 0,
    takeHome: 0,
    lateFilingPenalty: 0,
    latePaymentPenalty: 0,
    interestCharges: 0,
    totalWithPenalties: 0,
    isLate: false,
    monthsLate: 0
  })

  const [showResults, setShowResults] = useState(false)

  const generateForm1040 = () => {
    const form = `
═══════════════════════════════════════════════════════════
                    U.S. INDIVIDUAL INCOME TAX RETURN
                           FORM 1040
                      Tax Year ${inputs.taxYear}
═══════════════════════════════════════════════════════════

FILING STATUS: ${inputs.filingStatus === 'single' ? 'Single' : 'Married Filing Jointly'}

INCOME
─────────────────────────────────────────────────────────
Gross Business Income                    $${parseFloat(inputs.grossIncome || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}

ADJUSTMENTS & DEDUCTIONS
─────────────────────────────────────────────────────────
Business Expenses                        $${parseFloat(inputs.businessExpenses || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}
Additional Deductions                    $${parseFloat(inputs.deductions || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}

Taxable Income                          $${results.taxableIncome.toLocaleString('en-US', { minimumFractionDigits: 2 })}

TAX COMPUTATION
─────────────────────────────────────────────────────────
Federal Tax                             $${results.federalTax.toLocaleString('en-US', { minimumFractionDigits: 2 })}
${inputs.state !== 'federal-only' ? `State Tax                               $${results.stateTax.toLocaleString('en-US', { minimumFractionDigits: 2 })}` : ''}

Tax Credits                             ($${parseFloat(inputs.credits || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })})

Total Tax Due                           $${results.totalTax.toLocaleString('en-US', { minimumFractionDigits: 2 })}
${results.isLate ? `
PENALTIES & INTEREST (Late Filing)
─────────────────────────────────────────────────────────
Months Late: ${results.monthsLate}
Failure to File Penalty                 $${results.lateFilingPenalty.toLocaleString('en-US', { minimumFractionDigits: 2 })}
Failure to Pay Penalty                  $${results.latePaymentPenalty.toLocaleString('en-US', { minimumFractionDigits: 2 })}
Interest Charges                        $${results.interestCharges.toLocaleString('en-US', { minimumFractionDigits: 2 })}

TOTAL AMOUNT DUE (with penalties)       $${results.totalWithPenalties.toLocaleString('en-US', { minimumFractionDigits: 2 })}
` : ''}

Effective Tax Rate: ${results.effectiveRate.toFixed(2)}%

═══════════════════════════════════════════════════════════
Generated by CommerceCult Tax Calculator
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

⚠️ IMPORTANT: This is an estimate only. Please consult with
a licensed tax professional before filing your actual taxes.
═══════════════════════════════════════════════════════════
`
    
    // Create and download the file
    const blob = new Blob([form], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Tax_Form_1040_${inputs.taxYear}_Estimate.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generateScheduleC = () => {
    const scheduleC = `
═══════════════════════════════════════════════════════════
              SCHEDULE C - PROFIT OR LOSS FROM BUSINESS
                       (Sole Proprietorship)
                      Tax Year ${inputs.taxYear}
═══════════════════════════════════════════════════════════

INCOME
─────────────────────────────────────────────────────────
Gross receipts or sales                 $${parseFloat(inputs.grossIncome || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}

EXPENSES
─────────────────────────────────────────────────────────
Total Business Expenses                 $${parseFloat(inputs.businessExpenses || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}

NET PROFIT (LOSS)
─────────────────────────────────────────────────────────
Net Profit                              $${(parseFloat(inputs.grossIncome || '0') - parseFloat(inputs.businessExpenses || '0')).toLocaleString('en-US', { minimumFractionDigits: 2 })}

This amount should be reported on Form 1040, Schedule 1, Line 3.

═══════════════════════════════════════════════════════════
EXPENSE CATEGORIES TO TRACK:
─────────────────────────────────────────────────────────
□ Advertising                    □ Office Expenses
□ Car and Truck Expenses         □ Rent or Lease
□ Commissions and Fees           □ Repairs and Maintenance
□ Contract Labor                 □ Supplies
□ Depreciation                   □ Taxes and Licenses
□ Insurance                      □ Travel and Meals
□ Interest                       □ Utilities
□ Legal and Professional         □ Wages
═══════════════════════════════════════════════════════════

Generated by CommerceCult Tax Calculator
Date: ${new Date().toLocaleDateString()}

⚠️ IMPORTANT: Keep all receipts and documentation for at
least 7 years. Consult a tax professional for proper filing.
═══════════════════════════════════════════════════════════
`
    
    const blob = new Blob([scheduleC], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Schedule_C_${inputs.taxYear}_Estimate.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const calculateTax = () => {
    const income = parseFloat(inputs.grossIncome) || 0
    const expenses = parseFloat(inputs.businessExpenses) || 0
    const deductions = parseFloat(inputs.deductions) || 0
    const credits = parseFloat(inputs.credits) || 0
    const taxYear = parseInt(inputs.taxYear)
    
    // Calculate if filing is late
    const currentDate = new Date()
    const currentYear = currentDate.getFullYear()
    const currentMonth = currentDate.getMonth() + 1
    
    // Tax filing deadline is April 15
    let dueDate = new Date(taxYear + 1, 3, 15) // April 15 of following year
    let monthsLate = 0
    let isLate = false
    
    if (currentDate > dueDate) {
      isLate = true
      const diffTime = Math.abs(currentDate.getTime() - dueDate.getTime())
      monthsLate = Math.ceil(diffTime / (1000 * 60 * 60 * 24 * 30))
    }
    
    // Calculate taxable income
    const taxableIncome = Math.max(0, income - expenses - deductions)
    
    // 2024 Federal Tax Brackets (simplified)
    let federalTax = 0
    if (inputs.filingStatus === 'single') {
      if (taxableIncome <= 11000) {
        federalTax = taxableIncome * 0.10
      } else if (taxableIncome <= 44725) {
        federalTax = 1100 + (taxableIncome - 11000) * 0.12
      } else if (taxableIncome <= 95375) {
        federalTax = 5147 + (taxableIncome - 44725) * 0.22
      } else if (taxableIncome <= 182100) {
        federalTax = 16290 + (taxableIncome - 95375) * 0.24
      } else if (taxableIncome <= 231250) {
        federalTax = 37104 + (taxableIncome - 182100) * 0.32
      } else if (taxableIncome <= 578125) {
        federalTax = 52832 + (taxableIncome - 231250) * 0.35
      } else {
        federalTax = 174238.25 + (taxableIncome - 578125) * 0.37
      }
    } else {
      // Married filing jointly brackets
      if (taxableIncome <= 22000) {
        federalTax = taxableIncome * 0.10
      } else if (taxableIncome <= 89050) {
        federalTax = 2200 + (taxableIncome - 22000) * 0.12
      } else if (taxableIncome <= 190750) {
        federalTax = 10294 + (taxableIncome - 89050) * 0.22
      } else if (taxableIncome <= 364200) {
        federalTax = 32580 + (taxableIncome - 190750) * 0.24
      } else if (taxableIncome <= 462500) {
        federalTax = 74208 + (taxableIncome - 364200) * 0.32
      } else if (taxableIncome <= 693750) {
        federalTax = 105664 + (taxableIncome - 462500) * 0.35
      } else {
        federalTax = 186601.5 + (taxableIncome - 693750) * 0.37
      }
    }
    
    // Apply tax credits
    federalTax = Math.max(0, federalTax - credits)
    
    // Estimate state tax (simplified - using average state tax rates)
    let stateTax = 0
    if (inputs.state !== 'federal-only') {
      stateTax = taxableIncome * 0.05 // Average state tax rate
    }
    
    const totalTax = federalTax + stateTax
    
    // Calculate late filing penalties if applicable
    let lateFilingPenalty = 0
    let latePaymentPenalty = 0
    let interestCharges = 0
    
    if (isLate && totalTax > 0) {
      // Failure to File Penalty: 5% of unpaid taxes per month, up to 25%
      lateFilingPenalty = Math.min(totalTax * 0.05 * monthsLate, totalTax * 0.25)
      
      // Failure to Pay Penalty: 0.5% per month, up to 25%
      latePaymentPenalty = Math.min(totalTax * 0.005 * monthsLate, totalTax * 0.25)
      
      // Interest on unpaid taxes: approximately 8% annual (0.67% monthly)
      interestCharges = totalTax * 0.0067 * monthsLate
    }
    
    const totalWithPenalties = totalTax + lateFilingPenalty + latePaymentPenalty + interestCharges
    const effectiveRate = income > 0 ? (totalTax / income) * 100 : 0
    const takeHome = income - totalWithPenalties
    
    setResults({
      taxableIncome,
      federalTax,
      stateTax,
      totalTax,
      effectiveRate,
      takeHome,
      lateFilingPenalty,
      latePaymentPenalty,
      interestCharges,
      totalWithPenalties,
      isLate,
      monthsLate
    })
    setShowResults(true)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setInputs({
      ...inputs,
      [e.target.name]: e.target.value
    })
    setShowResults(false)
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-900 via-green-900/20 to-gray-900 py-12 px-4">
      <FreeTrialBanner />
      
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <Link 
            href="/calculators"
            className="inline-block mb-4 text-green-400 hover:text-green-300 transition"
          >
            ← Back to Calculators
          </Link>
          <h1 className="text-5xl font-bold text-white mb-4">
            💰 Business Tax Calculator
          </h1>
          <p className="text-xl text-gray-400">
            Estimate your business taxes and plan your finances
          </p>
          <p className="text-sm text-amber-400 mt-2">
            ⚠️ For informational purposes only. Consult a tax professional for accurate tax advice.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Input Section */}
          <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl border border-green-500/20 p-8">
            <h2 className="text-2xl font-bold text-white mb-6">Tax Information</h2>
            
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Gross Business Income ($)
                </label>
                <input
                  type="number"
                  name="grossIncome"
                  value={inputs.grossIncome}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                  placeholder="100000"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Business Expenses ($)
                </label>
                <input
                  type="number"
                  name="businessExpenses"
                  value={inputs.businessExpenses}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                  placeholder="30000"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Additional Deductions ($)
                </label>
                <input
                  type="number"
                  name="deductions"
                  value={inputs.deductions}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                  placeholder="5000"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Tax Credits ($)
                </label>
                <input
                  type="number"
                  name="credits"
                  value={inputs.credits}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                  placeholder="0"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Tax Year
                </label>
                <select
                  name="taxYear"
                  value={inputs.taxYear}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                >
                  <option value="2024">2024</option>
                  <option value="2023">2023</option>
                  <option value="2022">2022</option>
                  <option value="2021">2021</option>
                  <option value="2020">2020</option>
                  <option value="2019">2019</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  Filing Status
                </label>
                <select
                  name="filingStatus"
                  value={inputs.filingStatus}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                >
                  <option value="single">Single</option>
                  <option value="married">Married Filing Jointly</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  State Tax
                </label>
                <select
                  name="state"
                  value={inputs.state}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 bg-gray-900 border border-green-500/30 rounded-lg text-white focus:outline-none focus:border-green-500 transition"
                >
                  <option value="federal-only">Federal Only</option>
                  <option value="with-state">Include State Tax (5% avg)</option>
                </select>
              </div>

              <button
                onClick={calculateTax}
                className="w-full py-4 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-400 hover:to-emerald-400 text-white font-bold rounded-lg shadow-[0_0_20px_rgba(0,255,0,0.3)] hover:shadow-[0_0_30px_rgba(0,255,0,0.5)] transition-all duration-300 transform hover:scale-105"
              >
                Calculate Taxes
              </button>
            </div>
          </div>

          {/* Results Section */}
          <div className="space-y-6">
            {showResults ? (
              <>
                {results.isLate && (
                  <div className="bg-red-900/40 backdrop-blur-sm rounded-xl border border-red-500/50 p-6">
                    <h3 className="text-xl font-bold text-red-400 mb-3 flex items-center gap-2">
                      ⚠️ Late Filing Detected
                    </h3>
                    <p className="text-red-300 mb-3">
                      You are filing approximately <strong>{results.monthsLate} months late</strong> for tax year {inputs.taxYear}.
                    </p>
                    <p className="text-sm text-red-200">
                      The IRS imposes penalties and interest on late filings. Consider filing immediately to minimize additional charges.
                    </p>
                  </div>
                )}

                <div className="bg-gradient-to-br from-green-900/40 to-emerald-900/40 backdrop-blur-sm rounded-xl border border-green-500/30 p-8">
                  <h2 className="text-2xl font-bold text-white mb-6">Tax Summary</h2>
                  
                  <div className="space-y-4">
                    <ResultRow 
                      label="Taxable Income"
                      value={results.taxableIncome}
                    />
                    <ResultRow 
                      label="Federal Tax"
                      value={results.federalTax}
                    />
                    {results.stateTax > 0 && (
                      <ResultRow 
                        label="State Tax"
                        value={results.stateTax}
                      />
                    )}
                    <div className="border-t border-green-500/30 pt-4">
                      <ResultRow 
                        label="Total Tax"
                        value={results.totalTax}
                        highlight
                      />
                    </div>
                    
                    {results.isLate && (
                      <>
                        <div className="border-t border-red-500/30 pt-4 mt-4">
                          <h3 className="text-lg font-bold text-red-400 mb-3">Late Filing Penalties</h3>
                          <ResultRow 
                            label="Failure to File Penalty (5%/mo)"
                            value={results.lateFilingPenalty}
                          />
                          <ResultRow 
                            label="Failure to Pay Penalty (0.5%/mo)"
                            value={results.latePaymentPenalty}
                          />
                          <ResultRow 
                            label="Interest Charges (~8% annual)"
                            value={results.interestCharges}
                          />
                        </div>
                        <div className="border-t border-red-500/30 pt-4">
                          <ResultRow 
                            label="Total Tax + Penalties"
                            value={results.totalWithPenalties}
                            highlight
                            isWarning
                          />
                        </div>
                      </>
                    )}
                    
                    <ResultRow 
                      label="Effective Tax Rate"
                      value={`${results.effectiveRate.toFixed(2)}%`}
                      isPercentage
                    />
                    <div className="border-t border-green-500/30 pt-4">
                      <ResultRow 
                        label="After-Tax Income"
                        value={results.takeHome}
                        highlight
                      />
                    </div>
                  </div>
                </div>

                {/* Form Generation Buttons */}
                <div className="bg-gradient-to-br from-blue-900/40 to-purple-900/40 backdrop-blur-sm rounded-xl border border-blue-500/30 p-6">
                  <h3 className="text-xl font-bold text-blue-400 mb-4">📄 Generate Tax Forms</h3>
                  <p className="text-sm text-gray-300 mb-4">
                    Download estimated tax forms based on your calculations
                  </p>
                  <div className="grid grid-cols-2 gap-4">
                    <button
                      onClick={generateForm1040}
                      className="px-6 py-3 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg"
                    >
                      📋 Form 1040
                    </button>
                    <button
                      onClick={generateScheduleC}
                      className="px-6 py-3 bg-purple-600 hover:bg-purple-500 text-white font-semibold rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg"
                    >
                      📊 Schedule C
                    </button>
                  </div>
                  <p className="text-xs text-gray-400 mt-3">
                    ⚠️ These are estimates only. Use for planning purposes. Consult a tax professional for official filings.
                  </p>
                </div>

                <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl border border-blue-500/20 p-6">
                  <h3 className="text-lg font-bold text-blue-400 mb-3">💡 Tax Planning Tips</h3>
                  <ul className="space-y-2 text-sm text-gray-300">
                    {results.isLate ? (
                      <>
                        <li>• <strong className="text-red-400">File immediately</strong> to stop penalties from accumulating</li>
                        <li>• Consider setting up a payment plan with the IRS if you can't pay in full</li>
                        <li>• File even if you can't pay - the failure-to-file penalty is much higher</li>
                      </>
                    ) : (
                      <>
                        <li>• Maximize deductible business expenses</li>
                        <li>• Consider quarterly estimated tax payments</li>
                      </>
                    )}
                    <li>• Track all receipts and expenses throughout the year</li>
                    <li>• Explore retirement account contributions (SEP IRA, Solo 401k)</li>
                    <li>• Consult with a tax professional for personalized advice</li>
                  </ul>
                </div>
              </>
            ) : (
              <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl border border-green-500/20 p-8 text-center">
                <div className="text-6xl mb-4">📊</div>
                <p className="text-gray-400">
                  Enter your tax information and click "Calculate Taxes" to see your results
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Additional Info */}
        <div className="mt-12 grid md:grid-cols-3 gap-6">
          <InfoCard
            icon="📋"
            title="Deductible Expenses"
            description="Office supplies, software, advertising, travel, home office, etc."
          />
          <InfoCard
            icon="💼"
            title="Self-Employment Tax"
            description="Additional 15.3% for Social Security and Medicare (not included here)"
          />
          <InfoCard
            icon="⚠️"
            title="Late Filing Penalties"
            description="5% per month failure to file + 0.5% per month failure to pay + interest"
          />
        </div>
      </div>
    </main>
  )
}

function ResultRow({ 
  label, 
  value, 
  highlight = false,
  isPercentage = false,
  isWarning = false
}: { 
  label: string
  value: number | string
  highlight?: boolean
  isPercentage?: boolean
  isWarning?: boolean
}) {
  const displayValue = typeof value === 'number' && !isPercentage
    ? `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    : value

  return (
    <div className={`flex justify-between items-center ${highlight ? 'text-lg font-bold' : ''}`}>
      <span className="text-gray-300">{label}:</span>
      <span className={highlight ? (isWarning ? 'text-red-400' : 'text-green-400') : 'text-white'}>
        {displayValue}
      </span>
    </div>
  )
}

function InfoCard({ icon, title, description }: { icon: string; title: string; description: string }) {
  return (
    <div className="bg-gray-800/30 backdrop-blur-sm rounded-lg border border-green-500/10 p-6 text-center">
      <div className="text-4xl mb-3">{icon}</div>
      <h3 className="text-lg font-bold text-white mb-2">{title}</h3>
      <p className="text-sm text-gray-400">{description}</p>
    </div>
  )
}
